import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="flex min-h-screen justify-center items-center">
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <div className="max-w-xs rounded overflow-hidden shadow-lg my-2">
            <Image
              className="w-full"
              src="https://tailwindcss.com/img/card-top.jpg"
              width="800"
              height="847"
              alt="Sunset in the mountains"
            />
            <div className="px-6 py-4">
              <div className="font-bold text-xl mb-2">Next + Tailwind ❤️</div>
              <p className="text-grey-darker text-base">
                Next and Tailwind CSS are a match made in heaven, check out this article on how
                you can combine these two for your next app.
              </p>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        agus@senomas.com
      </footer>
    </div>
  )
}

export default Home
